// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs defs_constants_linux.go

package seccomp

const prSetNoNewPrivs = 0x26

const (
	seccompSetModeStrict = 0x0

	seccompSetModeFilter = 0x1
)

const x32SyscallMask = 0x40000000

const (
	ActionKillThread  Action = 0x0
	ActionKillProcess Action = 0x80000000
	ActionTrap        Action = 0x30000
	ActionErrno       Action = 0x50000
	ActionTrace       Action = 0x7ff00000
	ActionLog         Action = 0x7ffc0000
	ActionAllow       Action = 0x7fff0000
	ActionNotify      Action = 0x7fc00000
)

const (
	errnoEPERM  = 0x1
	errnoENOSYS = 0x26
)

const (
	FilterFlagTSync FilterFlag = 0x1

	FilterFlagNewFilter FilterFlag = 0x8

	FilterFlagLog FilterFlag = 0x2
)
